package com.example.ibsbms.service;

import com.example.ibsbms.dto.ShareholderCreateRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ShareholderWorkflowService {

    private final ShareholderService shareholderService;
    private final WorkflowIdService workflowIdService;

    public ShareholderWorkflowService(
            ShareholderService shareholderService,
            WorkflowIdService workflowIdService) {

        this.shareholderService = shareholderService;
        this.workflowIdService = workflowIdService;
    }

    @Transactional
    public void submitCreateForApproval(
            ShareholderCreateRequest request,
            String makerId,
            String makerIp) {

        /*
         * The Folio BO supplied by the browser must never be trusted.
         */
        request.getBasicInfo().setFolioBo(null);

        /*
         * Generate the complete proposal JSON.
         */
        String proposalJson =
                shareholderService.buildCreateProposalJson(request);

        /*
         * CHANGE_ID is currently generated by the temporary
         * abstraction. The remaining database-generated IDs
         * will be configured once we have Oracle access.
         */
        String changeId =
                workflowIdService.generateChangeId();

        System.out.println("======================================");
        System.out.println("MAKER SUBMISSION");
        System.out.println("======================================");
        System.out.println("Change ID : " + changeId);
        System.out.println("Maker ID  : " + makerId);
        System.out.println("Maker IP  : " + makerIp);
        System.out.println("Operation : SHAREHOLDER_CREATE");
        System.out.println("Status    : PENDING_CHECKER");
        System.out.println("--------------------------------------");
        System.out.println(proposalJson);
        System.out.println("======================================");

        /*
         * IMPORTANT:
         *
         * We intentionally do NOT insert anything into Oracle yet.
         *
         * Once the actual Oracle ID-generation mechanism is verified,
         * this method will:
         *
         * 1. Generate/reserve FOLIO_BO
         * 2. Insert T_SHAREHOLDER_CHANGE_REQUEST
         * 3. Generate REQUEST_ID
         * 4. Insert T_APPROVAL_REQUEST
         * 5. Generate ACTION_ID
         * 6. Insert T_APPROVAL_ACTION
         *
         * No final shareholder tables are touched here.
         */
    }
}